### ISSUE TITLE
Webapp Blazor Integrity Check Fails on localhost

### ISSUE THREAD

**Issue by themooer1** [revenz/FileFlows#125]
When running a clean instance of FileFlows in Docker

`docker run --name=FileFlows --rm -p 5000:5000  revenz/fileflows:0.7.1`
`docker run --name=FileFlows --rm -p 5000:5000  revenz/fileflows:0.8.0`
`docker run --name=FileFlows --rm -p 5000:5000  revenz/fileflows:0.8.1`
`docker run --name=FileFlows --rm -p 5000:5000  revenz/fileflows:develop`

The WebGUI does not load in Firefox or Chrome 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8960671/174465115-732ba72d-6a6f-4fc2-b128-b125856a76c0.png">

**Comment by revenz** [comment]
dont use develop, thats completely unstable and will  just lead to problems.

Follow the docker instructions on the downloads page or on dockerhub, they should work.

**Comment by themooer1** [comment]
When using this docker compose file (identical to the example except that it uses docker volumes), the same error occurs.

```
services:
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - data:/app/Data
      - logs:/app/Logs
      - media:/media  #optional
    ports:
      - 5000:5000
    restart: unless-stopped
volumes:
  data:
  logs:
  media:
```

**Comment by revenz** [comment]
your volumes look wrong

**Comment by themooer1** [comment]
The should just be blank volumes.  The same happens when I use regular bind-mounts.

```
services:
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /tmp/fileflows/data:/app/Data
      - /tmp/fileflows/logs:/app/Logs
      - /tmp/fileflows/media:/media  #optional
    ports:
      - 5000:5000
    restart: unless-stopped
```

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/174465586-86ee069a-21bf-4edf-9ede-0958dee05e53.png)

these are what i use for mine

**Comment by themooer1** [comment]
Have you seen integrity checks failing in the browser during development or when running on localhost?  I figured it might be related to this (https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures)[https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures], but it seems odd that the webapp fails to load with or without any volumes mounted.

**Comment by revenz** [comment]
I've seen it with blazor before, if you build then the \n get converted to \r\n on commit.   But if the docker image was bad, everyone would be having issue.  So that seems like a red herring.

so best to start with the basics and check those.

**Comment by themooer1** [comment]
That's what I figured (though I was able to replicate the crash on my local machine and on a Kubernetes cluster with mounts very similar to yours.

```
        - hostPath:
            path: /mnt/Alastor/fileflows/data
          name: data
        - hostPath:
            path: /mnt/Alastor/fileflows/logs
          name: logs
        - hostPath:
            path: /mnt/Alastor/media
          name: media
        - hostPath:
            path: /mnt/Alastor/fileflows/temp
```

I can start a Linux VM to copy your mounts exactly, but I figure mounting `/tmp/fileflows/...` should be equivalent to mounting `/mnt/docker/fileflows/...`
