### ISSUE TITLE
Docker build for arm64

### ISSUE THREAD

**Issue by JoshLoecker** [revenz/FileFlows#26]
Is it possible to get a docker build for ARM 64? I am using a raspberry pi 4 as a node, and when I use the following docker-compose file, I get an error: `fileflows-node | standard_init_linux.go:228: exec user process caused: exec format error`

docker-compose.yaml:
```
services:
  fileflows:
    image: revenz/fileflows-node
    container_name: fileflows-node
    environment:
      - ServerUrl=http://192.168.50.31:5000/
      - TempPath=/media/.fileflows_temp
    volumes:
      - /media/elements/data/media:/media
    restart: unless-stopped
```
