### ISSUE TITLE
[Feature Request] Default Mappings and All Libraries as Docker ENV

### ISSUE THREAD

**Issue by reavessm** [revenz/FileFlows#98]
This may take a lot of work, but could greatly improve the node on-boarding process.

I am running OpenShift and have FileFlow nodes as a DaemonSet, which means everytime I upgrade the cluster, all the nodes get deleted and recreated, which means they show up as new nodes with different IDs in FF.  Then I have to go in and manually type all of my folder mappings, click enable, increase the runner count and change the processing to 'All Libraries'.  This problem would also arise with any Cloud/Kubernetes environment that supports scaling (there's no point in auto scaling from 3 to 10 nodes if I have to manually edit every node through the UI).

I think a good workflow would be to describe as much as possible in the docker-compose or daemon-set.yml so all I have to do is click 'Enable' in the UI, (or alternatively have a PreShared Key to auto-enable nodes?)

I think a good format could be like:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  ...
spec:
  ...
  template:
    ...
    spec:
      containers:
        - name: fileflows
          image: docker.io/revenz/fileflows:latest
          env:
            - name: ServerUrl
              value: https://fileflows.domain.com
            - name: FFNODE
              value: "1"
            - name: Mappings
              value: "['/path/to/media/on/server':'/path/to/media/on/node','/second/path':'/second/path']"
            - name: AllLibraries
              value: "1"
            - name: RunnerCount
              value: "1"
``` 

FileFlows is an amazing tool that helped me save over 1.5 TB and counting, and I think this feature can make FF more accessible to a number of people.
